name = "Simple deposit"

input_csv = """type, client, tx, amount
deposit, 1, 1, 10.0\
"""

[output]
transactions_in_dispute = []

[[output.clients]]
id = 1
available = 10_0000
held = 0
locked = false

