name = "Disputed tx can't be resolved two times"

input_csv = """type, client, tx, amount
deposit, 1, 1, 10
dispute, 1, 1,
resolve, 1, 1,
resolve, 1, 1,
"""

[output]
transactions_in_dispute = []

[[output.clients]]
id = 1
available = 10_0000
held = 0
locked = false
