name = "Disputed tx can be resolved then re disputed"

input_csv = """type, client, tx, amount
deposit, 1, 1, 10
dispute, 1, 1,
resolve, 1, 1,
dispute, 1, 1,
"""

[output]
transactions_in_dispute = [1]

[[output.clients]]
id = 1
available = 0
held = 10_0000
locked = false
