name = "Deposit doesnt overflow client account"

input_csv = """type, client, tx, amount
deposit, 1, 1, 422337203600000000
deposit, 1, 2, 1
"""

[output]
transactions_in_dispute = []

[[output.clients]]
id = 1
available = 1_0000
held = 0
locked = false
